spring.datasource.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.jdbc.initialize-schema=always
spring.datasource.hikari.maximum-pool-size=50

# ActiveMQ config for memory broker
spring.activemq.in-memory=true
spring.activemq.pool.enabled=false
spring.jms.listener.auto-startup=true
spring.activemq.packages.trust-all=true

# Batch
spring.main.allow-bean-definition-overriding=true
spring.batch.job.enabled=false

# Logs
logging.level.org.springframework.batch=DEBUG
logging.level.org.springframework.integration=DEBUG
logging.level.org.springframework.transaction=DEBUG
